# Week 8 (Tue) - Class Activities in CS 315

You are given the file `netflix_top10_countries.tsv` in the folder data, solve the following tasks using it.

**Table of Contents**

1. [Q1: Load the file](#q1)
2. [Q2: Show number of rows](#q2)
3. [Q3: Show column names](#q3)
4. [Q4: Show number of total countries](#q4)
5. [Q5: Show number of TV series](#q5)
6. [Q6: Number of TV series in South Korea](#q6)
7. [Q7: Total weeks of Squid Games in Italy ](#q7)
8. [Q8: Time frame for a given country](#q8)
9. [Q9: Is number of weeks in ranking equal?](#q9)
10. [Q10: Country with fewest weeks](#q10)

<a id="q1"></a>
### Q1: Load the file

In [2]:
import pandas as pd 
df = pd.read_csv("netflix_top10_countries.tsv", sep= "\t")
df.head()

,country_name,country_iso2,week,category,weekly_rank,show_title,season_title,cumulative_weeks_in_top_10
0,Argentina,AR,2026-10-04,Films,1,UNABOMBER,NaN,2
1,Argentina,AR,2026-10-04,Films,2,The Equalizer 3,NaN,1
2,Argentina,AR,2026-10-04,Films,3,The Substance,NaN,1
3,Argentina,AR,2026-10-04,Films,4,Demon Slayer: Kimetsu no Yaiba Infinity Castle I,NaN,1
4,Argentina,AR,2026-10-04,Films,5,What a Father!,NaN,1

<a id="q2"></a>
### Q2: Show number of rows

In [3]:
df.shape
df.shape[0]

512200

<a id="q3"></a>
### Q3: Show column names

In [8]:
df.columns

Index(['country_name', 'country_iso2', 'week', 'category', 'weekly_rank',
       'show_title', 'season_title', 'cumulative_weeks_in_top_10'],
      dtype='object')

<a id="q4"></a>
### Q4: Show number of total countries

In [5]:
df.describe()

         weekly_rank  cumulative_weeks_in_top_10
count  512200.000000               512200.000000
mean        5.500000                    3.418557
std         2.872284                    6.057938
min         1.000000                    1.000000
25%         3.000000                    1.000000
50%         5.500000                    2.000000
75%         8.000000                    3.000000
max        10.000000                  134.000000

<a id="q5"></a>
### Q5: Show number of TV series

In [6]:
df[df["category"]== "TV"]["show_title"]

10              Not a Stranger
11                 My Sad Dead
12           The Final Problem
13        Shaque: Trust No One
14                East of Eden
                  ...
512195              Reply 1988
512196           Nevertheless,
512197       Too Hot to Handle
512198      Record of Ragnarok
512199    Crash Landing on You
Name: show_title, Length: 256100, dtype: object

<a id="q6"></a>
### Q6: Number of TV series in South Korea

In [11]:
df[df["country_name"]== "South Korea"]
df[(df["country_name"]== "South Korea") & (df["category"] == "TV")]["show_title"]

424210         Kian’s Bizarre B&B
424211    Marriage of Convenience
424212                The Scandal
424213    Four Hands, Two Sonatas
424214                  I am Solo
                   ...
429695              Nevertheless,
429696             The Iron Squad
429697         Mad for Each Other
429698                  My Mister
429699                   Sex/Life
Name: show_title, Length: 2750, dtype: object

<a id="q7"></a>
### Q7: Total weeks of Squid Game in Italy

In [ ]:
#df[df["country_name"]== "Italy"]
#df[(df["country_name"]== "Italy") & (df["show_title"]== "Squid Game")]
df[(df["country_name"]== "Italy") & (df["show_title"]== "Squid Game")]["week"]

204717    2025-08-10
204734    2025-08-03
204752    2025-07-27
204772    2025-07-20
204790    2025-07-13
204796    2025-07-13
204799    2025-07-13
204810    2025-07-06
204814    2025-07-06
204816    2025-07-06
204830    2025-06-29
205238    2025-02-09
205254    2025-02-02
205273    2025-01-26
205291    2025-01-19
205297    2025-01-19
205310    2025-01-12
205314    2025-01-12
205330    2025-01-05
205332    2025-01-05
205350    2024-12-29
205353    2024-12-29
208476    2022-01-02
208494    2021-12-26
208512    2021-12-19
208531    2021-12-12
208551    2021-12-05
208575    2021-11-28
208592    2021-11-21
208611    2021-11-14
208630    2021-11-07
208650    2021-10-31
208670    2021-10-24
208690    2021-10-17
208710    2021-10-10
208730    2021-10-03
208751    2021-09-26
Name: week, dtype: object

<a id="q8"></a>
### Q8: Time frame for a given country

Write a function that given a country name prints out the start and end date of their rankings.

Once you have created the function, call it for a few countries to test it.

In [19]:
def start_end(df, country):
    weeks = df[df["country_name"] == country]["week"]
    print (f" {country} Start {weeks.min()} and End: {weeks.max()}. ")

start_end(df, "South Korea")

 South Korea Start 2021-07-04 and End: 2026-10-04.

<a id="q9"></a>
### Q9: Is number of weeks equal for each country?

The total number of weeks in the rankings is `len(df['week'].unique())`.

The total number of countries is `len(df['country_name'].unique())`.  

For every week, each country has 20 rows.   

If they all stayed the same number of weeks, then the product of these three weeks would be the same as the total number of rows.

In [20]:
df.groupby("country_name")["week"] == 1

False

We should have expected this to be `False` since we saw in Q8 that Russia stopped being in the rankings after it attacked Ukraine in February 2022.

<a id="q10"></a>
### Q10: Country with fewest weeks

Write a one-liner that will show the country with the fewest weeks in the Netflix rankings